image: "python:3"

before_script:
  - python3 -V
  - pip install -r requirements.txt
  - pip install pdoc3

test:
  script:
    - python -m unittest discover

docs:
  script:
    - pdoc3 --html --force -output-dir docs netzwerkprogrammierung
  artifacts:
    paths:
      - docs